---
title: "test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message = FALSE, echo = FALSE}
library(multipleOutcomes)
library(dplyr)
library(survival)
options(digits = 2)

# helper: add a per-row subject id, required by jointCovariance()
add_pid <- function(df) {
  df$pid <- paste0("s-", seq_len(nrow(df)))
  df
}

printObject <- function(obj){
  message(gsub('_', '::', deparse(substitute(obj))))
  message(paste0('Relative Efficiency: ', format(attr(obj, 'Rel. Eff.'), digits = 3)))
  print(obj)
}
```

```{r echo=FALSE}
data(pharmacoSmoking, package = 'asaur')

asaur_pharmacoSmoking <-
  pated(
    coxph_(Surv(time = ttr, event = relapse) ~ grp,           data_index = 1),
    glm_(age            ~ grp, family = "gaussian",           data_index = 1),
    glm_(yearsSmoking   ~ grp, family = "gaussian",           data_index = 1),
    glm_(priorAttempts  ~ grp, family = "gaussian",           data_index = 1),
    glm_(longestNoSmoke ~ grp, family = "gaussian",           data_index = 1),
    glm_(gender         ~ grp, family = "binomial",           data_index = 1),
    glm_(I(race == 'black')        ~ grp, family = "binomial", data_index = 1),
    glm_(I(race == 'hispanic')     ~ grp, family = "binomial", data_index = 1),
    glm_(I(race == 'white')        ~ grp, family = "binomial", data_index = 1),
    glm_(I(employment == 'ft')     ~ grp, family = "binomial", data_index = 1),
    glm_(I(employment == 'pt')     ~ grp, family = "binomial", data_index = 1),
    glm_(I(levelSmoking == 'heavy')~ grp, family = "binomial", data_index = 1),
    data = list(add_pid(pharmacoSmoking %>%
                          mutate(grp = ifelse(grp == 'combination', 1, 0))))
  )

printObject(asaur_pharmacoSmoking)
```

```{r echo=FALSE}
data(glioma, package = 'coin')

coin_glioma <-
  pated(
    coxph_(Surv(time = time, event = event)   ~ group, data_index = 1),
    glm_(age                ~ group, family = "gaussian", data_index = 1),
    glm_(sex                ~ group, family = "binomial", data_index = 1),
    glm_(I(histology == 'GBM') ~ group, family = "binomial", data_index = 1),
    data = list(add_pid(glioma %>%
                          mutate(group = ifelse(group == 'Control', 0, 1),
                                 event = 1 * event)))
  )

printObject(coin_glioma)
```

```{r echo=FALSE}
data(burn, package = 'iBST')

iBST_burn <-
  pated(
    coxph_(Surv(time = T3, event = D3) ~ Z1, data_index = 1),
    glm_(Z2 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z3 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z5 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z6 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z7 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z8 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z9 ~ Z1, family = "binomial", data_index = 1),
    glm_(Z10 ~ Z1, family = "binomial", data_index = 1),
    glm_(I(Z11 == 1) ~ Z1, family = "binomial", data_index = 1),
    glm_(I(Z11 == 2) ~ Z1, family = "binomial", data_index = 1),
    glm_(I(Z11 == 3) ~ Z1, family = "binomial", data_index = 1),
    glm_(Z4 ~ Z1, family = "gaussian", data_index = 1),
    data = list(add_pid(burn))
  )

printObject(iBST_burn)
```

```{r echo=FALSE}
data(d.oropha.rec, package = 'invGauss')

invGauss_d.oropha.rec <-
  pated(
    coxph_(Surv(time = time, event = status) ~ treatm, data_index = 1),
    glm_(I(sex == 1) ~ treatm, family = "gaussian", data_index = 1),
    glm_(age         ~ treatm, family = "gaussian", data_index = 1),
    glm_(tstage      ~ treatm, family = "gaussian", data_index = 1),
    glm_(nstage      ~ treatm, family = "gaussian", data_index = 1),
    data = list(add_pid(d.oropha.rec %>%
                          mutate(treatm = ifelse(treatm == 2, 1, 0))))
  )

printObject(invGauss_d.oropha.rec)
```

```{r echo=FALSE}
data(aids.id, package = 'JM')

JM_aids.id <-
  pated(
    coxph_(Surv(time = Time, event = death) ~ drug, data_index = 1),
    glm_(CD4    ~ drug, family = "gaussian", data_index = 1),
    glm_(gender ~ drug, family = "binomial", data_index = 1),
    glm_(I(prevOI == 'AIDS')        ~ drug, family = "binomial", data_index = 1),
    glm_(I(AZT  == 'intolerance')   ~ drug, family = "binomial", data_index = 1),
    data = list(add_pid(aids.id %>%
                          mutate(drug = ifelse(drug == 'ddC', 1, 0))))
  )

printObject(JM_aids.id)
```

```{r echo=FALSE}
data(actg, package = 'multipleOutcomes')

mlr3proba_actg <-
  pated(
    coxph_(Surv(time = time, event = event) ~ tx, data_index = 1),
    glm_(strat2 ~ tx, family = "binomial", data_index = 1),
    glm_(sex    ~ tx, family = "binomial", data_index = 1),
    glm_(I(ivdrug == 1) ~ tx, family = "binomial", data_index = 1),
    glm_(I(raceth == 1) ~ tx, family = "binomial", data_index = 1),
    glm_(I(raceth == 2) ~ tx, family = "binomial", data_index = 1),
    glm_(I(raceth == 3) ~ tx, family = "binomial", data_index = 1),
    glm_(hemophil       ~ tx, family = "binomial", data_index = 1),
    glm_(I(karnof == 100) ~ tx, family = "binomial", data_index = 1),
    glm_(I(karnof == 90)  ~ tx, family = "binomial", data_index = 1),
    glm_(I(karnof == 80)  ~ tx, family = "binomial", data_index = 1),
    glm_(I(karnof == 70)  ~ tx, family = "binomial", data_index = 1),
    glm_(cd4      ~ tx, family = "gaussian", data_index = 1),
    glm_(priorzdv ~ tx, family = "gaussian", data_index = 1),
    glm_(age      ~ tx, family = "gaussian", data_index = 1),
    data = list(add_pid(actg %>%
                          mutate(event = 1 * (censor + censor_d > 0))))
  )

printObject(mlr3proba_actg)
```

```{r echo=FALSE}
data(dataOvarian1, package = 'joint.Cox')

set.seed(123)
dat <- dataOvarian1 %>%
  dplyr::select(t.event, event, CXCL12, NCOA3, PDPN, TEAD1, TIMP2, YWHAB)
n <- 500
ctrl <- dat[sample(nrow(dat), n, TRUE), ] %>% mutate(grp = 0)
trt  <- dat[sample(nrow(dat), n, TRUE), ] %>%
  mutate(t.event = t.event / .8, grp = 1)

joint.Cox_dataOvarian1 <-
  pated(
    coxph_(Surv(time = t.event, event = event) ~ grp, data_index = 1),
    glm_(CXCL12 ~ grp, family = "gaussian", data_index = 1),
    glm_(NCOA3  ~ grp, family = "gaussian", data_index = 1),
    glm_(PDPN   ~ grp, family = "gaussian", data_index = 1),
    glm_(TEAD1  ~ grp, family = "gaussian", data_index = 1),
    glm_(TIMP2  ~ grp, family = "gaussian", data_index = 1),
    glm_(YWHAB  ~ grp, family = "gaussian", data_index = 1),
    data = list(add_pid(rbind(ctrl, trt)))
  )

printObject(joint.Cox_dataOvarian1)
```

```{r echo=FALSE}
data(Pbc3, package = 'pec')

pec_Pbc3 <-
  pated(
    coxph_(Surv(time = days, event = event) ~ tment, data_index = 1),
    glm_(sex                 ~ tment, family = "binomial", data_index = 1),
    glm_(I(stage == 1)       ~ tment, family = "binomial", data_index = 1),
    glm_(I(stage == 2)       ~ tment, family = "binomial", data_index = 1),
    glm_(I(stage == 3)       ~ tment, family = "binomial", data_index = 1),
    glm_(I(stage == 4)       ~ tment, family = "binomial", data_index = 1),
    glm_(gibleed             ~ tment, family = "binomial", data_index = 1),
    glm_(age                 ~ tment, family = "gaussian", data_index = 1),
    glm_(crea                ~ tment, family = "gaussian", data_index = 1),
    glm_(bili                ~ tment, family = "gaussian", data_index = 1),
    glm_(alkph               ~ tment, family = "gaussian", data_index = 1),
    glm_(asptr               ~ tment, family = "gaussian", data_index = 1),
    glm_(weight              ~ tment, family = "gaussian", data_index = 1),
    data = list(add_pid(Pbc3 %>%
                          mutate(event = ifelse(status == 0, 0, 1))))
  )

printObject(pec_Pbc3)
```

```{r echo=FALSE}
data(cost, package = 'pec')
set.seed(10)
n <- 300
ctrl <- cost[sample(nrow(cost), n, TRUE), ] %>% mutate(trt = 0)
trt  <- cost[sample(nrow(cost), n, TRUE), ] %>%
  mutate(time = time / .8, trt = 1)
dat <- rbind(ctrl, trt)

set.seed(1)
pec_cost <-
  pated(
    coxph_(Surv(time = time, event = status) ~ trt, data_index = 1),
    glm_(age         ~ trt, family = "gaussian", data_index = 1),
    glm_(strokeScore ~ trt, family = "gaussian", data_index = 1),
    glm_(cholest     ~ trt, family = "gaussian", data_index = 1),
    glm_(sex         ~ trt, family = "binomial", data_index = 1),
    glm_(hypTen      ~ trt, family = "binomial", data_index = 1),
    glm_(ihd         ~ trt, family = "binomial", data_index = 1),
    glm_(prevStroke  ~ trt, family = "binomial", data_index = 1),
    glm_(othDisease  ~ trt, family = "binomial", data_index = 1),
    glm_(alcohol     ~ trt, family = "binomial", data_index = 1),
    glm_(diabetes    ~ trt, family = "binomial", data_index = 1),
    glm_(smoke       ~ trt, family = "binomial", data_index = 1),
    glm_(atrialFib   ~ trt, family = "binomial", data_index = 1),
    glm_(hemor       ~ trt, family = "binomial", data_index = 1),
    data = list(add_pid(dat))
  )

printObject(pec_cost)
```

```{r echo=FALSE}
data(GBSG2, package = 'pec')

pec_GBSG2 <-
  pated(
    coxph_(Surv(time = time, event = cens) ~ horTh, data_index = 1),
    glm_(tsize    ~ horTh, family = "gaussian", data_index = 1),
    glm_(pnodes   ~ horTh, family = "gaussian", data_index = 1),
    glm_(progrec  ~ horTh, family = "gaussian", data_index = 1),
    glm_(I(tgrade == 'I')   ~ horTh, family = "binomial", data_index = 1),
    glm_(I(tgrade == 'II')  ~ horTh, family = "binomial", data_index = 1),
    glm_(I(tgrade == 'III') ~ horTh, family = "binomial", data_index = 1),
    data = list(add_pid(GBSG2 %>%
                          mutate(horTh = ifelse(horTh == 'yes', 1, 0))))
  )

printObject(pec_GBSG2)
```

```{r echo=FALSE}
data(follic, package = 'randomForestSRC')

randomForestSRC_follic <-
  pated(
    coxph_(Surv(time = time, event = status) ~ ch, data_index = 1),
    glm_(age ~ ch, family = "gaussian", data_index = 1),
    glm_(hgb ~ ch, family = "gaussian", data_index = 1),
    data = list(add_pid(follic %>%
                          mutate(clinstg = ifelse(clinstg == 1, 1, 0),
                                 ch      = ifelse(ch      == 'Y', 1, 0),
                                 status  = ifelse(status  == 0, 0, 1))))
  )

printObject(randomForestSRC_follic)
```
